export const THEMES = {
  mono_print: {
    id: 'mono_print', name: 'Ink-Saver B&W',
    bg: '#ffffff',
    keyAlpha: '#ffffff',    keyAlphaText: '#000000',
    keyModifier: '#f3f4f6', keyModifierText: '#000000',
    keyAccent: '#e5e7eb',   keyAccentText: '#000000',
    boardColor: '#000000',
  },
  gmk_olivia: {
    id: 'gmk_olivia', name: 'GMK Olivia',
    bg: '#1c1c1c',
    keyAlpha: '#f1e3dc',    keyAlphaText: '#1a1a1a',
    keyModifier: '#2a2a2a', keyModifierText: '#f1e3dc',
    keyAccent: '#eab8b1',   keyAccentText: '#1a1a1a',
    boardColor: '#0e0e0e',
  },
  gmk_laser: {
    id: 'gmk_laser', name: 'GMK Laser',
    bg: '#0d0a1b',
    keyAlpha: '#005f73',    keyAlphaText: '#e0f7fa',
    keyModifier: '#1b1834', keyModifierText: '#00e5ff',
    keyAccent: '#ff007f',   keyAccentText: '#ffffff',
    boardColor: '#06040f',
  },
  gmk_carbon: {
    id: 'gmk_carbon', name: 'GMK Carbon',
    bg: '#1e1e1e',
    keyAlpha: '#eae6df',    keyAlphaText: '#1c1c1c',
    keyModifier: '#3a3a3a', keyModifierText: '#f0a060',
    keyAccent: '#ff6600',   keyAccentText: '#1c1c1c',
    boardColor: '#111111',
  },
  sleek_dark: {
    id: 'sleek_dark', name: 'Cyber Slate',
    bg: '#0f172a',
    keyAlpha: '#1e293b',    keyAlphaText: '#f1f5f9',
    keyModifier: '#334155', keyModifierText: '#f1f5f9',
    keyAccent: '#3b82f6',   keyAccentText: '#ffffff',
    boardColor: '#020617',
  },
  minimal_light: {
    id: 'minimal_light', name: 'Light',
    bg: '#f0f4f8',
    keyAlpha: '#ffffff',    keyAlphaText: '#0f172a',
    keyModifier: '#dde3ec', keyModifierText: '#1e293b',
    keyAccent: '#1e3a5f',   keyAccentText: '#ffffff',
    boardColor: '#c8d3df',
  },
  everforest: {
    id: 'everforest', name: 'Everforest',
    bg: '#2d353b',
    keyAlpha: '#3d484d',    keyAlphaText: '#d3c6aa',
    keyModifier: '#272e33', keyModifierText: '#83c092',
    keyAccent: '#a7c080',   keyAccentText: '#1e2326',
    boardColor: '#1e2326',
  },
};
